name: fitnessstudio-management-system

services:
  gateway:
    build:
      context: nginx
    ports:
      - "8800:80"
    networks:
      - fsms-client
      - fsms-server
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: frontend/fsms
      dockerfile: Dockerfile.prd
    environment:
      - NODE_ENV=production
      - EXPO_PUBLIC_NGINX=yes
    networks:
      - fsms-client
      - fsms-server
    expose:
      - "80"

  backend:
    build:
      context: backend
    expose:
      - "3000"
    #ports:
    #  - "3000:3000"
    networks:
      - fsms-server
    depends_on:
      - fsms-db

  fsms-db:
    build:
      context: db
    ports:
      - "3307:3306"
    networks:
      - fsms-client
      - fsms-server

volumes:
  frontend_node_modules: {}

networks:
  fsms-client:
    driver: bridge
  fsms-server:
    driver: bridge
    internal: true
